version: '3.8'
name: datagenie
services:
  chatapp:
    build: .
    ports:
      - "8501:8501"
    image: datagenie
    # env_file:
    #   - .env
    networks:
      custom_network:
        ipv4_address: 172.28.1.2
    environment:
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=${CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER}
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER}
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZUREOPENAIENGINE=${AZUREOPENAIENGINE}
      - AZUREOPENAIKEY=${AZUREOPENAIKEY}
      - DATABASETYPE=${DATABASETYPE}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASS=${SNOWFLAKE_PASS}
      - ACCOUNT=${ACCOUNT}
      - WAREHOUSE=${WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - ALLOWEDSCHEMAS=${ALLOWEDSCHEMAS}
      - ROLE=${ROLE}
      - APPTITLE=${APPTITLE}
      - GETHELPURL=${GETHELPURL}
      - SUBMITTICKETURL=${SUBMITTICKETURL}
    depends_on:
      - chromasdb
  chromasdb:
    image: "chromadb/chroma" 
    ports:
      - "8000:8000"
    # env_file:
    #   - .env2
    environment:
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=${CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER}
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER}
    volumes:
      - "db-data:/var/lib/chromadb"
    networks:
      custom_network:
        ipv4_address: 172.28.1.3
volumes:
  db-data:

networks:
  custom_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16